Update to EveEveRefTypes model to combat error
Fix to combat the error:

production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '('' in /var/www/seat/app/models/EveEveRefTypes.php:10